method: bayes
metric:
  name: eval/accuracy
  goal: maximize

early_terminate:
  type: hyperband
  min_iter: 2

parameters:
  rollout_batch_size:
    values: [64, 128, 256, 512]
  db_size:
    values: [512, 1024, 2048]
  n_ei_steps:
    values: [3, 5, 8]

command:
  - ${env}
  - python
  - -m
  - cs336_alignment.ei
  - --wandb-project
  - cs336-ei
  - --wandb-mode
  - online
  - --device-train
  - cuda:0
  - --device-vllm
  - cuda:1
  - --train-data-path
  - data/math/train.jsonl
  - --test-data-path
  - data/math/val.jsonl
  - --model-path
  - data/math/Qwen2.5-Math-1.5B
  - ${args}
